USERS_COLLECTION = "users"
DEVICE_COLLECTION = "devices"
TOKEN_COLLECTION = "tokens"
SESSION_COLLECTION = "sessions"
EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND'
INVALID_PASSWORD = 'INVALID_PASSWORD'
USER_DISABLED = 'USER_DISABLED'
EMAIL_EXISTS = 'EMAIL_EXISTS'
